name: CodeCov

on:
  push:
    paths:
      - '**.cs'
      - '**.yml'
  pull_request:
    paths:
      - '**.cs'
      - '**.yml'
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
      - name: Set GoalApiKey
        id: setgoalapikey
        shell: bash
        run: |
          if [ "$GOAL_API_KEY" != "" ]; then
            dotnet user-secrets set "GoalApiKey" "$GOAL_API_KEY" --project Goal/src/jiraF.Goal.API/
          else
            dotnet user-secrets set "GoalApiKey" "12345testApiKey" --project Goal/src/jiraF.Goal.API/
          fi
        env:
          GOAL_API_KEY: ${{ secrets.GOAL_API_KEY }}
      - name: Restore dependencies
        run: dotnet restore Goal
      - name: Build
        run: dotnet build Goal --no-restore
      - name: Test
        run: dotnet test Goal --no-build --verbosity normal --collect:"XPlat Code Coverage"
      - name: Report Codecov
        uses: codecov/codecov-action@v3
        with:
          path_to_write_report: ./coverage/codecov1.xml