name: Goal codecov

on:
  push:
    paths:
      - '**.cs'
      - '**.yml'
  pull_request:
    paths:
      - '**.cs'
      - '**.yml'
    branches: [ main ]
jobs:
  filter-folder:
    runs-on: ubuntu-latest
    outputs:
     is_folder_changed: ${{ steps.changes.outputs.goal }}
    steps:
      - uses: actions/checkout@v3
      - name: Paths Changes Filter
        uses: dorny/paths-filter@v2.10.2
        id: changes
        with:
          filters: |
            goal:
              - 'Goal/**'
  build:
    needs: [filter-folder]
    if: needs.filter-folder.outputs.is_folder_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Set GoalApiKey
        id: setgoalapikey
        shell: bash
        run: |
          if [ "$GOAL_API_KEY" != "" ]; then
            dotnet user-secrets set "GoalApiKey" "$GOAL_API_KEY" --project Goal/src/jiraF.Goal.API/
          else
            dotnet user-secrets set "GoalApiKey" "12345testApiKey" --project Goal/src/jiraF.Goal.API/
          fi
        env:
          GOAL_API_KEY: ${{ secrets.GOAL_API_KEY }}
      - name: Restore dependencies
        run: dotnet restore Goal
      - name: Build
        run: dotnet build Goal --no-restore
      - name: Test
        run: dotnet test Goal --no-build --verbosity normal --collect:"XPlat Code Coverage"
      - name: Report Codecov
        uses: codecov/codecov-action@v3