name: Member microservice SonarCloud
on:
  push:
    paths:
      - '**.cs'
      - '**.yml'
  pull_request:
    paths:
      - '**.cs'
      - '**.yml'
    types: [opened, synchronize, reopened]
jobs:
  check-registry-secrets:
   name: Check if container registry information was set on secrets
   runs-on: ubuntu-latest
   outputs:
     have_secrets: ${{ steps.setvar.outputs.have_secrets }}
   steps:
     - id: setvar
       run: |
         if [[ "${{ secrets.SONAR_TOKEN }}" != "" ]]; \
         then
           echo "Secrets to use a container registry were configured in the repo"
           echo "::set-output name=have_secrets::true"
         else
           echo "Secrets to use a container registry were not configured in the repo"
           echo "::set-output name=have_secrets::false"
         fi
  filter-folder:
    runs-on: ubuntu-latest
    outputs:
     is_folder_changed: ${{ steps.changes.outputs.member }}
    steps:
      - uses: actions/checkout@v3
      - name: Paths Changes Filter
        uses: dorny/paths-filter@v2.10.2
        id: changes
        with:
          filters: |
            member:
              - 'Member/**'
  build:
    needs: [check-registry-secrets, filter-folder]
    if: needs.filter-folder.outputs.is_folder_changed == 'true'
    name: Build
    runs-on: windows-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      - name: Build and analyze
        if: needs.check-registry-secrets.outputs.have_secrets == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          dotnet tool install --global dotnet-coverage
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"KurnakovMaksim_jiraF" /o:"kurnakovmaksim" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
          dotnet restore Member
          dotnet build Member --no-restore
          dotnet test Member --no-build --verbosity normal
          dotnet-coverage collect 'dotnet test Member' -f xml -o 'coverage.xml'
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"