name: User microservice Build/Test

on:
  push:
    paths:
      - '**.cs'
      - '**.yml'
  pull_request:
    paths:
      - '**.cs'
      - '**.yml'
    branches: [ main ]

jobs:
  filter-folder:
    runs-on: ubuntu-latest
    outputs:
     is_folder_changed: ${{ steps.changes.outputs.user }}
    steps:
      - uses: actions/checkout@v3
      - name: Paths Changes Filter
        uses: dorny/paths-filter@v2.10.2
        id: changes
        with:
          filters: |
            user:
              - 'User/**'
  build:
    needs: [filter-folder]
    if: needs.filter-folder.outputs.is_folder_changed == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore User
    - name: Build
      run: dotnet build User --no-restore
    - name: Test
      run: dotnet test User --no-build --verbosity normal
