name: Member codecov

on:
  push:
    paths:
      - '**.cs'
      - '**.yml'
  pull_request:
    paths:
      - '**.cs'
      - '**.yml'
    branches: [ main ]
jobs:
  filter-folder:
    runs-on: ubuntu-latest
    outputs:
     is_folder_changed: ${{ steps.changes.outputs.member }}
    steps:
      - uses: actions/checkout@v3
      - name: Paths Changes Filter
        uses: dorny/paths-filter@v2.10.2
        id: changes
        with:
          filters: |
            member:
              - 'Member/**'
  build:
    needs: [filter-folder]
    if: needs.filter-folder.outputs.is_folder_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Set MemberApiKey
        id: setmemberapikey
        shell: bash
        run: |
          if [ "$MEMBER_API_KEY" != "" ]; then
            dotnet user-secrets set "MemberApiKey" "$MEMBER_API_KEY" --project Member/src/jiraF.Member.API/
          else
            dotnet user-secrets set "MemberApiKey" "12345testApiKey" --project Member/src/jiraF.Member.API/
          fi
        env:
          MEMBER_API_KEY: ${{ secrets.MEMBER_API_KEY }}
      - name: Restore dependencies
        run: dotnet restore Member
      - name: Build
        run: dotnet build Member --no-restore
      - name: Test
        run: dotnet test Member --no-build --verbosity normal --collect:"XPlat Code Coverage"
      - name: Report Codecov
        uses: codecov/codecov-action@v3